export interface IndustryPreset {
  id: string;
  name: string;
  emoji: string;
  productsLabel: string;
  skuLabel: string;
  priceLabel: string;
  ordersLabel: string;
  customersLabel: string;
  staffLabel: string;
}

export const INDUSTRY_PRESETS: IndustryPreset[] = [
  {
    id: 'retail',
    name: 'Retail & Store',
    emoji: '🛍️',
    productsLabel: 'Products',
    skuLabel: 'SKU / Barcode',
    priceLabel: 'Price',
    ordersLabel: 'Orders',
    customersLabel: 'Customers',
    staffLabel: 'Staff',
  },
  {
    id: 'restaurant',
    name: 'Restaurant & Cafe',
    emoji: '🍽️',
    productsLabel: 'Dishes / Menu',
    skuLabel: 'Item Code',
    priceLabel: 'Rate',
    ordersLabel: 'KOT / Orders',
    customersLabel: 'Guests',
    staffLabel: 'Waiters / Chefs',
  },
  {
    id: 'clinic',
    name: 'Clinic & Healthcare',
    emoji: '🏥',
    productsLabel: 'Medicines & Services',
    skuLabel: 'Rx Code',
    priceLabel: 'Consultation Fee',
    ordersLabel: 'Appointments',
    customersLabel: 'Patients',
    staffLabel: 'Doctors / Nurses',
  },
  {
    id: 'salon',
    name: 'Salon & Spa',
    emoji: '✂️',
    productsLabel: 'Services & Packages',
    skuLabel: 'Service Code',
    priceLabel: 'Charge',
    ordersLabel: 'Bookings',
    customersLabel: 'Clients',
    staffLabel: 'Stylists / Therapists',
  },
  {
    id: 'wholesale',
    name: 'Wholesale & B2B',
    emoji: '📦',
    productsLabel: 'Bulk Goods',
    skuLabel: 'Batch Code',
    priceLabel: 'Wholesale Rate',
    ordersLabel: 'Sales Orders',
    customersLabel: 'Dealers / Buyers',
    staffLabel: 'Sales Reps',
  },
  {
    id: 'auto',
    name: 'Auto & Garage',
    emoji: '🚗',
    productsLabel: 'Spare Parts & Repairs',
    skuLabel: 'Part #',
    priceLabel: 'Unit Cost',
    ordersLabel: 'Job Cards',
    customersLabel: 'Vehicle Owners',
    staffLabel: 'Mechanics / Techs',
  },
  {
    id: 'fitness',
    name: 'Fitness & Gym',
    emoji: '🏋️',
    productsLabel: 'Memberships & Classes',
    skuLabel: 'Plan Code',
    priceLabel: 'Membership Fee',
    ordersLabel: 'Enrollments',
    customersLabel: 'Members',
    staffLabel: 'Personal Trainers',
  },
  {
    id: 'hotel',
    name: 'Hotel & Lodging',
    emoji: '🏨',
    productsLabel: 'Rooms & Amenities',
    skuLabel: 'Room #',
    priceLabel: 'Nightly Tariff',
    ordersLabel: 'Reservations',
    customersLabel: 'Guests',
    staffLabel: 'Front Desk Staff',
  },
  {
    id: 'education',
    name: 'School & Coaching',
    emoji: '🏫',
    productsLabel: 'Courses & Batches',
    skuLabel: 'Course Code',
    priceLabel: 'Tuition Fee',
    ordersLabel: 'Enrollments',
    customersLabel: 'Students',
    staffLabel: 'Teachers / Tutors',
  },
  {
    id: 'services',
    name: 'Services & Agency',
    emoji: '⚖️',
    productsLabel: 'Services & Projects',
    skuLabel: 'Project ID',
    priceLabel: 'Hourly Rate',
    ordersLabel: 'Contracts',
    customersLabel: 'Clients',
    staffLabel: 'Consultants',
  },
  {
    id: 'jewelry',
    name: 'Jewelry & Gems',
    emoji: '💎',
    productsLabel: 'Ornaments & Gems',
    skuLabel: 'Hallmark Code',
    priceLabel: 'Rate / Gram',
    ordersLabel: 'Sales Slips',
    customersLabel: 'Buyers',
    staffLabel: 'Artisans / Jewelers',
  },
  {
    id: 'laundry',
    name: 'Laundry & Cleaners',
    emoji: '🧺',
    productsLabel: 'Garments & Dry Clean',
    skuLabel: 'Tag Code',
    priceLabel: 'Washing Charge',
    ordersLabel: 'Pickup Orders',
    customersLabel: 'Customers',
    staffLabel: 'Delivery Staff',
  },
  {
    id: 'construction',
    name: 'Construction & Supply',
    emoji: '🏗️',
    productsLabel: 'Materials & Supplies',
    skuLabel: 'Material ID',
    priceLabel: 'Unit Rate',
    ordersLabel: 'Purchase Slips',
    customersLabel: 'Contractors',
    staffLabel: 'Site Supervisors',
  },
  {
    id: 'hardware_rental',
    name: 'IT Gadgets & Rental',
    emoji: '💻',
    productsLabel: 'Laptops & Gadgets',
    skuLabel: 'Serial #',
    priceLabel: 'Rental Rate',
    ordersLabel: 'Rental Agreements',
    customersLabel: 'Enterprise Clients',
    staffLabel: 'Technicians',
  },
  {
    id: 'vet',
    name: 'Vet & Pet Care',
    emoji: '🐾',
    productsLabel: 'Pet Care & Vaccines',
    skuLabel: 'Pet Code',
    priceLabel: 'Treatment Fee',
    ordersLabel: 'Consultations',
    customersLabel: 'Pet Parents',
    staffLabel: 'Veterinarians',
  },
  {
    id: 'catering',
    name: 'Event & Catering',
    emoji: '🎨',
    productsLabel: 'Catering & Setup',
    skuLabel: 'Event ID',
    priceLabel: 'Package Rate',
    ordersLabel: 'Event Bookings',
    customersLabel: 'Event Hosts',
    staffLabel: 'Coordinators',
  },
  {
    id: 'travel',
    name: 'Travel & Tourism',
    emoji: '✈️',
    productsLabel: 'Tour Packages',
    skuLabel: 'Tour Code',
    priceLabel: 'Package Price',
    ordersLabel: 'Itineraries',
    customersLabel: 'Travelers',
    staffLabel: 'Travel Agents',
  },
  {
    id: 'photography',
    name: 'Photo Studio',
    emoji: '📸',
    productsLabel: 'Photoshoots & Edit',
    skuLabel: 'Session ID',
    priceLabel: 'Session Fee',
    ordersLabel: 'Shoot Bookings',
    customersLabel: 'Clients',
    staffLabel: 'Photographers',
  },
  {
    id: 'logistics',
    name: 'Logistics & Freight',
    emoji: '🚚',
    productsLabel: 'Shipments & Parcels',
    skuLabel: 'Tracking #',
    priceLabel: 'Freight Charge',
    ordersLabel: 'Waybills',
    customersLabel: 'Consignees',
    staffLabel: 'Drivers',
  },
  {
    id: 'bakery',
    name: 'Bakery & Cakes',
    emoji: '🍞',
    productsLabel: 'Cakes & Pastries',
    skuLabel: 'Batch #',
    priceLabel: 'Unit Price',
    ordersLabel: 'Pre-Orders',
    customersLabel: 'Customers',
    staffLabel: 'Bakers',
  },
];
